---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - ansible.builtin.include_vars:
        file: ../../defaults/main.yml

    - name: Get paperless_ngx redis container state
      community.docker.docker_container:
        name: "{{ paperless_ngx_redis_container_name }}"
      register: result_redis

    - name: Get paperless_ngx db container state
      community.docker.docker_container:
        name: "{{ paperless_ngx_db_container_name }}"
      register: result_db

    - name: Get paperless_ngx container state
      community.docker.docker_container:
        name: "{{ paperless_ngx_uiserver_container_name }}"
      register: result

    - name: Check if paperless_ngx containers are running
      ansible.builtin.assert:
        that:
          - result_redis.container['State']['Status'] == "running"
          - result_redis.container['State']['Restarting'] == false
          - result_db.container['State']['Status'] == "running"
          - result_db.container['State']['Restarting'] == false
          - result.container['State']['Status'] == "running"
          - result.container['State']['Restarting'] == false
